## The following two functions cache the inverse of a specific inversible matrix

## makeCacheMatrix creates and returns a list of functions
makeCacheMatrix <- function(x = matrix()) {
        inv <- NULL
        set <- function(y){
                x <<- y
                inv <<- NULL
        }
        get <- function()x
        setinv <- function(inverse) inv <<-inverse
        getinv <- function() inv
        list(set=set, get=get, setinv=setinv, getinv=getinv)
}


## cacheSolve takes the list generated by the above function 
##and either calculate and cache the inverse 
##or return the cached inverse
cacheSolve <- function(x, ...) {
        inv <- x$getinv()
        if(!is.null(inv)){
                message("getting cached inverse")
                return(inv)
        }
        data <- x$get()
        inv <- solve(data, ...)
        x$setinv(inv)
        inv
}
